FinanzasApp/Models/Cuenta.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FinanzasApp.Models
{
    public class Cuenta
    {
        public int Id { get; set; }
        public String Nombre { get; set; }
        public String Categoria { get; set; }
        public decimal Monto { get; set; }
 
    }
}

FinanzasApp/Models/ErrorViewModel.cs
using System;

namespace FinanzasApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FinanzasApp/Models/Gastos.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FinanzasApp.Models
{
    public class Gastos
    {
        public int Id { get; set; }
        public DateTime Fecha { get; set; }
        public String Descripcion { get; set; }
        public decimal Monto { get; set; }
        public Cuenta Cuenta { get; set; }
        public int CuentaId { get; set; }
    }
}

FinanzasApp/Models/Ingresos.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FinanzasApp.Models
{
    public class Ingresos
    {
        public int Id { get; set; }
        public DateTime Fecha { get; set; }
        public String Descripcion { get; set; }
        public decimal Monto { get; set; }
        public Cuenta Cuenta { get; set; }
        public int CuentaId { get; set; }
    }
}

FinanzasApp/Controllers/CuentaController.cs
using FinanzasApp.Interface;
using FinanzasApp.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FinanzasApp.Controllers
{
    public class CuentaController : Controller
    {
        private readonly ICuenta cuentaInterface;

        public CuentaController(ICuenta cuentaInterface)
        {
            this.cuentaInterface = cuentaInterface;
        }

        public IActionResult Index()
        {
            var listaCuentas = cuentaInterface.getLista();
            return View(listaCuentas);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Cuenta cuenta)
        {
            if (ModelState.IsValid)
            {
                cuentaInterface.createCuenta(cuenta);
                return RedirectToAction("Index");
            }

            return View();
        }

       
    }
}

FinanzasApp/Controllers/GastosController.cs
using FinanzasApp.Interface;
using FinanzasApp.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FinanzasApp.Controllers
{
    public class GastosController : Controller
    {
        private readonly IGasto gastoInterface;
        private readonly ICuenta cuentaInterface;

        public GastosController(IGasto gastoInterface, ICuenta cuentaInterface)
        {
            this.gastoInterface = gastoInterface;
            this.cuentaInterface = cuentaInterface;
        }
        public IActionResult Index()
        {
            var listaGastos = gastoInterface.getLista();
            return View(listaGastos);
        }

        public IActionResult Create()
        {
            ViewBag.Cuenta = cuentaInterface.getLista();

            return View();
        }

        [HttpPost]
        public IActionResult Create(Gastos gastos)
        {

            var cuen = cuentaInterface.Cuenta(gastos.CuentaId);

            if(gastos.Monto > cuen.Monto)
            {
                return RedirectToAction("Index");

            }

            if (ModelState.IsValid)
            {
                gastoInterface.createGastos(gastos);
                return RedirectToAction("Index");
            }

            return View();
        }
    }
}

FinanzasApp/Controllers/HomeController.cs
using FinanzasApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace FinanzasApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FinanzasApp/Controllers/IngresosController.cs
using FinanzasApp.Interface;
using FinanzasApp.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FinanzasApp.Controllers
{
    public class IngresosController : Controller
    {
        private readonly IIngresos ingresoInterface;
        private readonly ICuenta cuentaInterface;

        public IngresosController(IIngresos ingresoInterface, ICuenta cuentaInterface)
        {
            this.ingresoInterface = ingresoInterface;
            this.cuentaInterface = cuentaInterface;
        }

        public IActionResult Index()
        {
            var listaIngresos = ingresoInterface.getLista();
            return View(listaIngresos);
        }

        public IActionResult Create()
        {
            ViewBag.Cuenta = cuentaInterface.getLista();
            return View();
        }

        [HttpPost]
        public IActionResult Create(Ingresos ingresos)
        {
            if (ModelState.IsValid)
            {
                ingresoInterface.createIngresos(ingresos);
                return RedirectToAction("Index");
            }

            return View();
        }
    }
}

FinanzasApp/Views/Cuenta/Create.cshtml
@model FinanzasApp.Models.Cuenta

@{
    ViewData["Title"] = "Crear una Cuenta";
}

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3>Crear Nueva Cuenta</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-10">
            <div class="card">
                <div class="card-body">
                    <form method="post" asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label class="control-label"> Nombre</label>
                            <input id="Nombre" asp-for="Nombre" class="form-control" />
                            <span asp-for="Nombre" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Categoria" class="control-label"></label>
                            <select asp-for="Categoria" id="Categoria" class="form-control">
                                <option selected>Seleccionar una Categoria</option>
                                <option value="Propia">Propia</option>
                                <option value="Credito">Crédito</option>
                            </select>
                            <span asp-validation-for="Categoria" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label"> Monto</label>
                            <input id="Monto" asp-for="Monto" class="form-control" />
                            <span asp-for="Monto" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" id="crearCuenta" value="Crear Cuenta" class="btn btn-primary" />
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

FinanzasApp/Views/Cuenta/Index.cshtml
@model IEnumerable<FinanzasApp.Models.Cuenta>

@{
    ViewData["Title"] = "Lista de Cuentas";
}

<div class="container">
    <div class="row ">
        <div class="col-sm-10">

        </div>
        <div class="col-sm-2">
            <a class="btn btn-success d-block" id="agregarNuevaCuenta" asp-action="Create" asp-controller="Cuenta"><i class="far fa-plus-square"></i></a>
        </div>
    </div>


    <div class="row mt-3 ">
        <div class="col-sm-12">
            @if (Model.Count() > 0)
            {
                <table class="table table-bordered" id="datatable">
                    <thead class="thead-dark">
                        <tr>
                            <td>Nombre</td>
                            <td>Categoria</td>
                            <td>Monto</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>@item.Nombre</td>
                            <td>@item.Categoria</td>
                            <td>@item.Monto</td>


                        </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <p>No existen registros</p>
            }
        </div>
    </div>
</div>

FinanzasApp/Views/Gastos/Create.cshtml
@model FinanzasApp.Models.Gastos

@{
    ViewData["Title"] = "Create";
    var cuenta = ViewBag.Cuenta;
}

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3>Crear Nuevos Gastos</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-10">
            <div class="card">
                <div class="card-body">

                    <form method="post" asp-action="Create">
                        <div class="form-group">
                            <label asp-for="CuentaId" class="control-label">Número Mesa</label>
                            <select asp-for="CuentaId" id="CuentaId" class="form-control">
                                <option>Seleccionar Cuenta</option>
                                @foreach (var item in cuenta)
                                {
                                    <option value="@item.Id">@item.Nombre</option>
                                }
                            </select>
                            <span asp-validation-for="CuentaId" class="text-danger"></span>
                        </div>


                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Descripcion" class="control-label">Descripción</label>
                            <input asp-for="Descripcion" id="Descripcion" class="form-control" />
                            <span asp-validation-for="Descripcion" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="Monto" class="control-label"></label>
                            <input asp-for="Monto" id="Monto" class="form-control" />
                            <span asp-validation-for="Monto" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <input type="submit" id="registrarGastos" value="Registrar Gastos" class="btn btn-primary" />
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

FinanzasApp/Views/Gastos/Index.cshtml
@model IEnumerable<FinanzasApp.Models.Gastos>

@{
    ViewData["Title"] = "Lista de Gastos";
}

<div class="container">
    <div class="row ">
        <div class="col-sm-10">

        </div>
        <div class="col-sm-2">
            <a class="btn btn-success d-block" id="agregarNuevoGasto" asp-action="Create" asp-controller="Gastos"><i class="far fa-plus-square"></i></a>
        </div>
    </div>


    <div class="row mt-3 ">
        <div class="col-sm-12">
            @if (Model.Count() > 0)
            {
                <table class="table table-bordered" id="datatable">
                    <thead class="thead-dark">
                        <tr>
                            <td>Cuenta</td>
                            <td>Fecha Gasto</td>
                            <td>Descripcion</td>
                            <td>Monto</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Cuenta.Nombre</td>
                                <td>@item.Fecha</td>
                                <td>@item.Descripcion</td>
                                <td>@item.Monto</td>

                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <p>No existen registros</p>
            }
        </div>
    </div>
</div>

FinanzasApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

FinanzasApp/Views/Ingresos/Create.cshtml
@model FinanzasApp.Models.Ingresos

@{
    ViewData["Title"] = "Create";
    var cuenta = ViewBag.Cuenta;
}

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3>Crear Nuevos Ingresos</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-10">
            <div class="card">
                <div class="card-body">

                    <form method="post" asp-action="Create">
                        <div class="form-group">
                            <label asp-for="CuentaId" class="control-label">Número Mesa</label>
                            <select asp-for="CuentaId" id="CuentaId" class="form-control">
                                <option>Seleccionar Cuenta</option>
                                @foreach (var item in cuenta)
                                {
                                    <option value="@item.Id">@item.Nombre</option>
                                }
                            </select>
                            <span asp-validation-for="CuentaId" class="text-danger"></span>
                        </div>


                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Descripcion" class="control-label">Descripción</label>
                            <input asp-for="Descripcion" id="Descripcion" class="form-control" />
                            <span asp-validation-for="Descripcion" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="Monto" class="control-label"></label>
                            <input asp-for="Monto" id="Monto" class="form-control" />
                            <span asp-validation-for="Monto" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <input type="submit" id="registrarIngresos" value="Registrar Ingresos" class="btn btn-primary" />
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

FinanzasApp/Views/Ingresos/Index.cshtml
@model IEnumerable<FinanzasApp.Models.Ingresos>

@{
    ViewData["Title"] = "Lista de Ingresos";
}

<div class="container">
    <div class="row ">
        <div class="col-sm-10">

        </div>
        <div class="col-sm-2">
            <a class="btn btn-success d-block" id="agregarNuevoIngreso" asp-action="Create" asp-controller="Ingresos"><i class="far fa-plus-square"></i></a>
        </div>
    </div>


    <div class="row mt-3 ">
        <div class="col-sm-12">
            @if (Model.Count() > 0)
            {
                <table class="table table-bordered" id="datatable">
                    <thead class="thead-dark">
                        <tr>
                            <td>Cuenta</td>
                            <td>Fecha Gasto</td>
                            <td>Descripcion</td>
                            <td>Monto</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Cuenta.Nombre</td>
                                <td>@item.Fecha</td>
                                <td>@item.Descripcion</td>
                                <td>@item.Monto</td>

                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <p>No existen registros</p>
            }
        </div>
    </div>
</div>

FinanzasApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FinanzasApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/e745eea8c3.js" crossorigin="anonymous"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FinanzasApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cuenta" id="goCuentas" asp-action="Index">Cuentas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Gastos" id="goGastos" asp-action="Index">Gastos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ingresos" id="goIngresos" asp-action="Index">Ingresos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - FinanzasApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>